language: node_js
node_js:
  - "8"
  - "6"
cache:
  directories:
  - node_modules # NPM packages
script:
  - npm run build
  - npm test
  - npm run lint
notifications:
  email:
    on_success: never
    on_failure: change
